"""
Signal Queue - Separates Signal Generation from Execution
==========================================================

Provides a thread-safe queue for decoupling signal generation (bots)
from signal execution (order placement).

Architecture:
    [Bots] --> generate signals --> [SignalQueue] --> [ExecutionWorker] --> [Alpaca]
    
Benefits:
- Bots focus on analysis, not order management
- Centralized order placement with rate limiting
- Priority execution (exits before entries)
- Audit trail of all signals generated vs executed
- Retry logic in one place

Signal Flow:
1. Bot detects opportunity -> creates TradeSignal
2. Bot calls signal_queue.push(signal)
3. ExecutionWorker (separate thread) pulls from queue
4. ExecutionWorker validates and places order via Alpaca
5. Result logged and signal marked complete

Usage:
    queue = get_signal_queue()
    
    # In bot:
    signal = TradeSignal(
        bot_id="crypto_core",
        symbol="BTC/USD",
        action="BUY",
        qty=0.01,
        order_type="MARKET",
        priority=SignalPriority.NORMAL
    )
    queue.push(signal)
    
    # ExecutionWorker runs in background, processing signals
"""

from typing import Dict, Any, Optional, List
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from queue import PriorityQueue, Empty
import threading
import time
import traceback

from ..core.logging import get_logger
from ..core.state import get_state, set_state
from ..core.halt import get_halt_manager
import uuid


def _generate_signal_id(prefix: str = "SIG") -> str:
    """Generate a unique signal ID."""
    return f"{prefix}_{uuid.uuid4().hex[:12]}"


class SignalPriority(Enum):
    """Priority levels for signal execution."""
    CRITICAL = 0   # Emergency exits, stop-losses
    HIGH = 1       # Take-profits, trailing stop exits
    NORMAL = 2     # Entry signals
    LOW = 3        # Opportunistic entries, scale-ins


class SignalAction(Enum):
    """Action types for signals."""
    BUY = "BUY"
    SELL = "SELL"
    EXIT = "EXIT"           # Close position
    EXIT_PARTIAL = "EXIT_PARTIAL"  # Partial close


class SignalStatus(Enum):
    """Status of a signal in the queue."""
    PENDING = "pending"
    PROCESSING = "processing"
    EXECUTED = "executed"
    FAILED = "failed"
    REJECTED = "rejected"   # Failed validation
    CANCELLED = "cancelled"


@dataclass
class TradeSignal:
    """
    A trade signal generated by a bot.
    
    Contains all information needed to execute an order.
    """
    bot_id: str
    symbol: str
    action: SignalAction
    qty: float
    order_type: str = "market"  # market, limit, stop, stop_limit
    limit_price: Optional[float] = None
    stop_price: Optional[float] = None
    time_in_force: str = "gtc"  # day, gtc, ioc, fok
    priority: SignalPriority = SignalPriority.NORMAL
    reason: str = ""
    
    # Metadata
    signal_id: str = field(default_factory=lambda: _generate_signal_id("SIG"))
    created_at: datetime = field(default_factory=datetime.now)
    status: SignalStatus = SignalStatus.PENDING
    
    # Execution tracking
    order_id: Optional[str] = None
    executed_at: Optional[datetime] = None
    executed_price: Optional[float] = None
    executed_qty: Optional[float] = None
    error_message: Optional[str] = None
    
    # Risk context (for validation)
    max_loss_usd: Optional[float] = None
    stop_loss_pct: Optional[float] = None
    take_profit_pct: Optional[float] = None
    
    def __lt__(self, other):
        """For priority queue ordering (lower priority value = higher priority)."""
        if self.priority.value != other.priority.value:
            return self.priority.value < other.priority.value
        return self.created_at < other.created_at
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert signal to dictionary for logging."""
        return {
            "signal_id": self.signal_id,
            "bot_id": self.bot_id,
            "symbol": self.symbol,
            "action": self.action.value,
            "qty": self.qty,
            "order_type": self.order_type,
            "limit_price": self.limit_price,
            "stop_price": self.stop_price,
            "priority": self.priority.name,
            "reason": self.reason,
            "status": self.status.value,
            "created_at": self.created_at.isoformat(),
            "order_id": self.order_id,
            "executed_at": self.executed_at.isoformat() if self.executed_at else None,
            "executed_price": self.executed_price,
            "error_message": self.error_message
        }


class SignalQueue:
    """
    Thread-safe priority queue for trade signals.
    
    Signals are processed in priority order:
    CRITICAL > HIGH > NORMAL > LOW
    
    Within same priority, FIFO order is maintained.
    """
    
    def __init__(self, max_size: int = 1000):
        self._queue: PriorityQueue = PriorityQueue(maxsize=max_size)
        self._logger = get_logger()
        self._lock = threading.Lock()
        
        # Stats
        self._stats = {
            "total_pushed": 0,
            "total_processed": 0,
            "total_executed": 0,
            "total_failed": 0,
            "total_rejected": 0,
            "by_priority": {p.name: 0 for p in SignalPriority},
            "by_bot": {}
        }
        self._stats_lock = threading.Lock()
        
        # Recent signals for audit
        self._recent_signals: List[TradeSignal] = []
        self._max_recent = 100
    
    def push(self, signal: TradeSignal) -> bool:
        """
        Push a signal to the queue.
        
        Returns True if signal was queued, False if queue is full.
        """
        try:
            self._queue.put_nowait(signal)
            
            with self._stats_lock:
                self._stats["total_pushed"] += 1
                self._stats["by_priority"][signal.priority.name] += 1
                
                if signal.bot_id not in self._stats["by_bot"]:
                    self._stats["by_bot"][signal.bot_id] = {"pushed": 0, "executed": 0}
                self._stats["by_bot"][signal.bot_id]["pushed"] += 1
            
            self._logger.log("signal_queued", signal.to_dict())
            return True
            
        except Exception as e:
            self._logger.error(f"Failed to queue signal: {e}")
            return False
    
    def pop(self, timeout: float = 1.0) -> Optional[TradeSignal]:
        """
        Pop the highest priority signal from the queue.
        
        Returns None if queue is empty after timeout.
        """
        try:
            signal = self._queue.get(timeout=timeout)
            signal.status = SignalStatus.PROCESSING
            
            with self._stats_lock:
                self._stats["total_processed"] += 1
            
            return signal
            
        except Empty:
            return None
    
    def mark_executed(self, signal: TradeSignal, order_id: str, 
                      price: float = None, qty: float = None):
        """Mark a signal as successfully executed."""
        signal.status = SignalStatus.EXECUTED
        signal.order_id = order_id
        signal.executed_at = datetime.now()
        signal.executed_price = price
        signal.executed_qty = qty
        
        with self._stats_lock:
            self._stats["total_executed"] += 1
            if signal.bot_id in self._stats["by_bot"]:
                self._stats["by_bot"][signal.bot_id]["executed"] += 1
        
        self._add_to_recent(signal)
        self._logger.log("signal_executed", signal.to_dict())
    
    def mark_failed(self, signal: TradeSignal, error: str):
        """Mark a signal as failed."""
        signal.status = SignalStatus.FAILED
        signal.error_message = error
        
        with self._stats_lock:
            self._stats["total_failed"] += 1
        
        self._add_to_recent(signal)
        self._logger.log("signal_failed", signal.to_dict())
    
    def mark_rejected(self, signal: TradeSignal, reason: str):
        """Mark a signal as rejected (failed validation)."""
        signal.status = SignalStatus.REJECTED
        signal.error_message = reason
        
        with self._stats_lock:
            self._stats["total_rejected"] += 1
        
        self._add_to_recent(signal)
        self._logger.log("signal_rejected", signal.to_dict())
    
    def _add_to_recent(self, signal: TradeSignal):
        """Add signal to recent list for audit."""
        with self._lock:
            self._recent_signals.append(signal)
            if len(self._recent_signals) > self._max_recent:
                self._recent_signals.pop(0)
    
    def get_stats(self) -> Dict[str, Any]:
        """Get queue statistics."""
        with self._stats_lock:
            return {
                **self._stats,
                "queue_size": self._queue.qsize(),
                "queue_empty": self._queue.empty()
            }
    
    def get_recent_signals(self, limit: int = 20) -> List[Dict[str, Any]]:
        """Get recent signals for audit/display."""
        with self._lock:
            return [s.to_dict() for s in self._recent_signals[-limit:]]
    
    def size(self) -> int:
        """Get current queue size."""
        return self._queue.qsize()
    
    def is_empty(self) -> bool:
        """Check if queue is empty."""
        return self._queue.empty()


class ExecutionWorker:
    """
    Background worker that processes signals from the queue.
    
    Runs in its own thread, pulling signals and placing orders.
    Includes validation, rate limiting, and retry logic.
    """
    
    def __init__(self, signal_queue: SignalQueue, interval_seconds: float = 0.5):
        self._queue = signal_queue
        self._interval = interval_seconds
        self._logger = get_logger()
        
        self._thread: Optional[threading.Thread] = None
        self._shutdown_event = threading.Event()
        self._running = False
        
        # Rate limiting
        self._last_order_time: Dict[str, float] = {}  # symbol -> timestamp
        self._min_order_interval = 1.0  # Min seconds between orders for same symbol
        
        # Stats
        self._loop_count = 0
        self._orders_placed = 0
    
    def _validate_signal(self, signal: TradeSignal) -> tuple[bool, str]:
        """
        Validate a signal before execution.
        
        Returns (is_valid, rejection_reason).
        """
        halt = get_halt_manager()
        
        # Check global halt for new entries
        if signal.action in [SignalAction.BUY] and halt.is_halted():
            return False, "Global halt active - no new entries"
        
        # Validate quantity
        if signal.qty <= 0:
            return False, f"Invalid quantity: {signal.qty}"
        
        # Validate limit price for limit orders
        if signal.order_type == "limit" and signal.limit_price is None:
            return False, "Limit order missing limit_price"
        
        # Rate limit check
        if signal.symbol in self._last_order_time:
            elapsed = time.time() - self._last_order_time[signal.symbol]
            if elapsed < self._min_order_interval:
                return False, f"Rate limited: {elapsed:.1f}s < {self._min_order_interval}s"
        
        return True, ""
    
    def _execute_signal(self, signal: TradeSignal) -> bool:
        """
        Execute a validated signal by placing an order.
        
        Returns True if order was placed successfully.
        """
        from .alpaca_client import get_alpaca_client
        
        try:
            alpaca = get_alpaca_client()
            
            # Build order parameters
            order_params = {
                "symbol": signal.symbol,
                "qty": signal.qty,
                "side": "buy" if signal.action in [SignalAction.BUY] else "sell",
                "type": signal.order_type,
                "time_in_force": signal.time_in_force,
                "client_order_id": signal.signal_id
            }
            
            if signal.limit_price:
                order_params["limit_price"] = signal.limit_price
            if signal.stop_price:
                order_params["stop_price"] = signal.stop_price
            
            # Submit order
            order = alpaca.submit_order(**order_params)
            
            # Update rate limit tracking
            self._last_order_time[signal.symbol] = time.time()
            self._orders_placed += 1
            
            # Mark signal as executed
            self._queue.mark_executed(
                signal,
                order_id=order.id,
                price=float(order.filled_avg_price) if order.filled_avg_price else None,
                qty=float(order.filled_qty) if order.filled_qty else None
            )
            
            return True
            
        except Exception as e:
            self._queue.mark_failed(signal, str(e))
            self._logger.error(f"Order execution failed: {e}")
            return False
    
    def _worker_loop(self):
        """Main worker loop."""
        self._logger.log("execution_worker_started", {
            "interval": self._interval
        })
        
        while not self._shutdown_event.is_set():
            self._loop_count += 1
            
            try:
                # Pull signal from queue
                signal = self._queue.pop(timeout=self._interval)
                
                if signal is None:
                    continue
                
                # Validate signal
                is_valid, reason = self._validate_signal(signal)
                
                if not is_valid:
                    self._queue.mark_rejected(signal, reason)
                    continue
                
                # Execute signal
                self._execute_signal(signal)
                
            except Exception as e:
                self._logger.error(f"Execution worker error: {e}")
                traceback.print_exc()
        
        self._logger.log("execution_worker_stopped", {
            "loop_count": self._loop_count,
            "orders_placed": self._orders_placed
        })
    
    def start(self):
        """Start the execution worker thread."""
        if self._running:
            return
        
        self._shutdown_event.clear()
        self._running = True
        
        self._thread = threading.Thread(
            target=self._worker_loop,
            name="ExecutionWorker",
            daemon=True
        )
        self._thread.start()
        
        self._logger.log("execution_worker_starting", {})
    
    def stop(self, timeout: float = 5.0):
        """Stop the execution worker."""
        if not self._running:
            return
        
        self._shutdown_event.set()
        
        if self._thread and self._thread.is_alive():
            self._thread.join(timeout=timeout)
        
        self._running = False
    
    def is_running(self) -> bool:
        """Check if worker is running."""
        return self._running and self._thread is not None and self._thread.is_alive()
    
    def get_stats(self) -> Dict[str, Any]:
        """Get worker statistics."""
        return {
            "running": self._running,
            "loop_count": self._loop_count,
            "orders_placed": self._orders_placed,
            "queue_stats": self._queue.get_stats()
        }


# Singleton instances
_signal_queue: Optional[SignalQueue] = None
_execution_worker: Optional[ExecutionWorker] = None
_lock = threading.Lock()


def get_signal_queue() -> SignalQueue:
    """Get or create the signal queue singleton."""
    global _signal_queue
    
    if _signal_queue is None:
        with _lock:
            if _signal_queue is None:
                _signal_queue = SignalQueue()
    
    return _signal_queue


def get_execution_worker() -> ExecutionWorker:
    """Get or create the execution worker singleton."""
    global _execution_worker, _signal_queue
    
    if _execution_worker is None:
        with _lock:
            if _execution_worker is None:
                queue = get_signal_queue()
                _execution_worker = ExecutionWorker(queue, interval_seconds=0.5)
    
    return _execution_worker


def start_execution_worker():
    """Start the execution worker (call at app startup)."""
    worker = get_execution_worker()
    worker.start()


def stop_execution_worker():
    """Stop the execution worker (call at app shutdown)."""
    global _execution_worker
    if _execution_worker:
        _execution_worker.stop()
